image: node:8.15.0

before_script:
  - apt-get update -yq \
    && apt-get install curl gnupg -yq \
    && curl -sL https://deb.nodesource.com/setup_8.x | bash \
    && apt-get install nodejs -yq \ 
    && apt-get install -y npm
  - npm install --save firebase-admin
  - npm install express --save
  - npm install shelljs
  - npm i --global mocha
  - npm i --save-dev mocha
  - npm i --save-dev chai

all_tests:
  script:
    - npm test
