before_script:
  - apt-get update && apt-get install nodejs && apt-get install npm
  - npm install --save firebase-admin
  - npm install express --save
  - npm install shelljs
  - npm i --global mocha
  - npm i --save-dev mocha
  - npm i --save-dev chai

all_tests:
  script:
    - npm test